// Hand-authored types mirroring supabase/migrations/*.sql.
// This is NOT generated by the Supabase CLI (no live project exists yet for this
// hackathon build) -- keep it in sync manually if the schema changes, or regenerate
// with `supabase gen types typescript` once a real project is provisioned.

export type AllergenStatus = 'safe' | 'contains' | 'may_contain';

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      allergens: {
        Row: {
          code: string;
          label: string;
          sort_order: number;
        };
        Insert: {
          code: string;
          label: string;
          sort_order?: number;
        };
        Update: {
          code?: string;
          label?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      restaurants: {
        Row: {
          id: string;
          osm_id: number;
          name: string;
          created_at: string;
          description: string | null;
          description_source: string | null;
          reviewed_at: string | null;
          verification: 'safe_bites' | 'restaurant';
        };
        Insert: {
          id?: string;
          osm_id: number;
          name: string;
          created_at?: string;
          description?: string | null;
          description_source?: string | null;
          reviewed_at?: string | null;
          verification?: 'safe_bites' | 'restaurant';
        };
        Update: {
          id?: string;
          osm_id?: number;
          name?: string;
          created_at?: string;
          description?: string | null;
          description_source?: string | null;
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          description: string | null;
          price: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          name: string;
          description?: string | null;
          price?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          name?: string;
          description?: string | null;
          price?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'menu_items_restaurant_id_fkey';
            columns: ['restaurant_id'];
            isOneToOne: false;
            referencedRelation: 'restaurants';
            referencedColumns: ['id'];
          },
        ];
      };
      menu_item_allergen_tags: {
        Row: {
          id: string;
          menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
        };
        Insert: {
          id?: string;
          menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
        };
        Update: {
          id?: string;
          menu_item_id?: string;
          allergen_code?: string;
          status?: AllergenStatus;
        };
        Relationships: [
          {
            foreignKeyName: 'menu_item_allergen_tags_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'menu_item_allergen_tags_allergen_code_fkey';
            columns: ['allergen_code'];
            isOneToOne: false;
            referencedRelation: 'allergens';
            referencedColumns: ['code'];
          },
        ];
      };
      ratings: {
        Row: {
          id: string;
          osm_id: number;
          restaurant_name: string;
          accuracy_rating: number;
          accommodation_rating: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          osm_id: number;
          restaurant_name: string;
          accuracy_rating: number;
          accommodation_rating: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          osm_id?: number;
          restaurant_name?: string;
          accuracy_rating?: number;
          accommodation_rating?: number;
          comment?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      menu_item_allergen_feedback: {
        Row: {
          id: string;
          menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
          comment: string | null;
          created_at: string;
          owner_hash: string | null;
          updated_at: string | null;
          report_count: number;
        };
        Insert: {
          id?: string;
          menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
          comment?: string | null;
          created_at?: string;
          owner_hash?: string | null;
          updated_at?: string | null;
          report_count?: number;
        };
        Update: {
          id?: string;
          menu_item_id?: string;
          allergen_code?: string;
          status?: AllergenStatus;
          comment?: string | null;
          created_at?: string;
          owner_hash?: string | null;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'menu_item_allergen_feedback_menu_item_id_fkey';
            columns: ['menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'menu_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'menu_item_allergen_feedback_allergen_code_fkey';
            columns: ['allergen_code'];
            isOneToOne: false;
            referencedRelation: 'allergens';
            referencedColumns: ['code'];
          },
        ];
      };
      community_menu_items: {
        Row: {
          id: string;
          osm_id: number;
          restaurant_name: string;
          name: string;
          description: string | null;
          price: number | null;
          created_at: string;
          owner_hash: string | null;
          updated_at: string | null;
          report_count: number;
        };
        Insert: {
          id?: string;
          osm_id: number;
          restaurant_name: string;
          name: string;
          description?: string | null;
          price?: number | null;
          created_at?: string;
          owner_hash?: string | null;
          updated_at?: string | null;
          report_count?: number;
        };
        Update: {
          id?: string;
          osm_id?: number;
          restaurant_name?: string;
          name?: string;
          description?: string | null;
          price?: number | null;
          created_at?: string;
          owner_hash?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      community_menu_item_allergen_tags: {
        Row: {
          id: string;
          community_menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
        };
        Insert: {
          id?: string;
          community_menu_item_id: string;
          allergen_code: string;
          status: AllergenStatus;
        };
        Update: {
          id?: string;
          community_menu_item_id?: string;
          allergen_code?: string;
          status?: AllergenStatus;
        };
        Relationships: [
          {
            foreignKeyName: 'community_menu_item_allergen_tags_community_menu_item_id_fkey';
            columns: ['community_menu_item_id'];
            isOneToOne: false;
            referencedRelation: 'community_menu_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'community_menu_item_allergen_tags_allergen_code_fkey';
            columns: ['allergen_code'];
            isOneToOne: false;
            referencedRelation: 'allergens';
            referencedColumns: ['code'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_menu_item_feedback: {
        Args: { p_menu_item_id: string; p_allergen_code: string; p_status: string; p_comment: string };
        Returns: Json;
      };
      update_menu_item_feedback: {
        Args: { p_id: string; p_owner_secret: string; p_status: string; p_comment: string };
        Returns: boolean;
      };
      delete_menu_item_feedback: {
        Args: { p_id: string; p_owner_secret: string };
        Returns: boolean;
      };
      create_community_menu_item: {
        Args: {
          p_osm_id: number;
          p_restaurant_name: string;
          p_name: string;
          p_description: string;
          p_price: number | null;
          p_tags: Json;
        };
        Returns: Json;
      };
      update_community_menu_item: {
        Args: {
          p_id: string;
          p_owner_secret: string;
          p_name: string;
          p_description: string;
          p_price: number | null;
          p_tags: Json;
        };
        Returns: boolean;
      };
      delete_community_menu_item: {
        Args: { p_id: string; p_owner_secret: string };
        Returns: boolean;
      };
      report_submission: {
        Args: { p_target_type: 'feedback' | 'community_item'; p_target_id: string; p_device_id: string };
        Returns: boolean;
      };
      my_rating: {
        Args: { p_osm_id: number; p_device_id: string };
        Returns: {
          accuracy_rating: number;
          accommodation_rating: number;
          comment: string | null;
          created_at: string;
          updated_at: string | null;
        }[];
      };
      submit_rating: {
        Args: {
          p_osm_id: number;
          p_restaurant_name: string;
          p_accuracy_rating: number;
          p_accommodation_rating: number;
          p_comment: string;
          p_device_id: string;
        };
        Returns: boolean;
      };
      request_review: {
        Args: { p_osm_id: number; p_restaurant_name: string; p_device_id: string };
        Returns: number;
      };
      review_request_status: {
        Args: { p_osm_id: number; p_device_id: string };
        Returns: { request_count: number; requested_by_me: boolean }[];
      };
    };
  };
}
